# Generated by Django 4.2.17 on 2024-12-19 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Мева номи')),
            ],
        ),
        migrations.CreateModel(
            name='FruitVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Нав номи')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='api.fruits', verbose_name='Мева')),
            ],
        ),
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garden_established_year', models.IntegerField(blank=True, null=True, verbose_name='Боғ барпо этилган йил')),
                ('total_area', models.FloatField(verbose_name='Жами ер майдони гектар')),
                ('irrigation_area', models.FloatField(default=0, verbose_name='Томчилатиб суғориш майдони')),
                ('fertility_score', models.FloatField(blank=True, null=True, verbose_name='Унумдорлиги банитет балли')),
                ('land_type', models.CharField(choices=[('лялими', 'Лялими'), ('тож олди', 'Тож олди'), ('адир', 'Адир'), ('сувли', 'Сувли')], max_length=10, verbose_name='Жойлашган тури')),
                ('is_fertile', models.BooleanField(default=True, verbose_name='Ҳосилли ёки ҳосилсиз')),
                ('fenced', models.BooleanField(default=False, verbose_name='Атрофи сетка билан ўралганлиги')),
                ('irrigation_systems_count', models.IntegerField(default=0, verbose_name='Қудуқлар сони')),
                ('pump_station_count', models.IntegerField(default=0, verbose_name='Насос станцияси сони')),
                ('reservoir_count', models.IntegerField(default=0, verbose_name='Ҳовузлар сони')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.district', verbose_name='Туман')),
            ],
        ),
        migrations.CreateModel(
            name='Trellis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trellis_installed_area', models.FloatField(default=0, verbose_name='Шпаллар ўрнатилган майдон')),
                ('trellis_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Шпаллер тури')),
                ('trellis_count', models.IntegerField(default=0, verbose_name='Шпаллар сони')),
                ('plantation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trellis', to='api.plantation')),
            ],
        ),
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Ажратилган йил')),
                ('contract_number', models.CharField(max_length=50, verbose_name='Субсидия шартнома рақами')),
                ('direction', models.CharField(max_length=100, verbose_name='Йўналиши')),
                ('amount', models.FloatField(verbose_name='Миқдори сўм')),
                ('efficiency', models.BooleanField(verbose_name='Самарадорлиги')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidies', to='api.plantation')),
            ],
        ),
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservoir_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ҳовуз тури')),
                ('reservoir_volume', models.FloatField(blank=True, null=True, verbose_name='Ҳовуз ҳажми')),
                ('plantation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservoir', to='api.plantation')),
            ],
        ),
        migrations.CreateModel(
            name='PlantationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plantation_images/', verbose_name='Расм')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.plantation')),
            ],
        ),
        migrations.CreateModel(
            name='PlantationFruitArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootstock', models.CharField(blank=True, max_length=100, null=True, verbose_name='Пайвантак номи')),
                ('planted_year', models.IntegerField(verbose_name='Экилган йили')),
                ('area', models.FloatField(verbose_name='Экин ер майдони гектар')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fruits', verbose_name='Мева тури')),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruit_areas', to='api.plantation', verbose_name='Плантация')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fruitvariety', verbose_name='Нави')),
            ],
        ),
        migrations.CreateModel(
            name='PlantationCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='api.plantation')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_type', models.CharField(choices=[('махаллий', 'Махаллий'), ('интенсив', 'Интенсив')], max_length=10, verbose_name='Маҳаллий ёки интенсив')),
                ('investment_foreign', models.FloatField(default=0, verbose_name='Хорижий инвестиция')),
                ('investment_local', models.FloatField(default=0, verbose_name='Маҳаллий инвестиция')),
                ('plantation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment', to='api.plantation')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Фермер хўжалиги номи')),
                ('founder_name', models.CharField(max_length=100, verbose_name='Таъсисчи номи')),
                ('director_name', models.CharField(max_length=100, verbose_name='Хўжалик директори')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон рақами')),
                ('address', models.TextField(verbose_name='Яшаш манзили')),
                ('inn', models.CharField(max_length=20, verbose_name='Ташкилот ИНН')),
                ('established_year', models.IntegerField(verbose_name='Ташкил этилган йил')),
                ('plantation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to='api.plantation')),
            ],
        ),
    ]
