# Generated by Django 4.2.17 on 2024-12-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fruits_fruitvariety_plantation_trellis_subsidy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantation',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Tekshirildi'),
        ),
        migrations.AddField(
            model_name='plantation',
            name='is_deleting',
            field=models.BooleanField(default=False, verbose_name='Ochirilishi kere'),
        ),
    ]
