# Generated by Django 4.2.17 on 2024-12-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_plantation_is_checked_plantation_is_deleting'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantation',
            name='prev_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Предыдущие данные'),
        ),
        migrations.AddField(
            model_name='plantation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
