# Generated by Django 4.2.17 on 2024-12-20 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_plantation_prev_data_plantation_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='plantation',
        ),
        migrations.AddField(
            model_name='plantation',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantations', to='api.farmer', verbose_name='Фермер'),
        ),
    ]
