# Generated by Django 4.2.17 on 2024-12-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_farmer_plantation_plantation_farmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='investment_foreign',
            new_name='investment_amount',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='investment_local',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='founder_name',
            field=models.CharField(max_length=100, verbose_name='Таъсисчи ismi'),
        ),
    ]
